// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Lighthouse API",
    "version": "1.0"
  },
  "host": "localhost",
  "basePath": "/",
  "paths": {
    "/lighthouse": {
      "get": {
        "responses": {
          "200": {
            "description": "All known lighthouses",
            "schema": {
              "$ref": "#/definitions/lighthouse"
            }
          }
        }
      }
    },
    "/lighthouse/state": {
      "post": {
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "address": {
                  "$ref": "#definitions/lighthouse/properties/address"
                },
                "state": {
                  "$ref": "#definitions/lighthouse/properties/state"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "State changed successfully",
            "schema": {
              "$ref": "#/definitions/lighthouse"
            }
          },
          "400": {
            "description": "Malformed request",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "429": {
            "description": "Rate limited (can only change state so often)",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/scan": {
      "post": {
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "timeout": {
                  "description": "how long to scan for (in seconds)",
                  "type": "integer",
                  "default": 5,
                  "maximum": 10,
                  "minimum": 1
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Rescan successfully completed",
            "schema": {
              "$ref": "#/definitions/lighthouse"
            }
          },
          "400": {
            "description": "Malformed request",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "429": {
            "description": "Rate limited (can only rescan so often)",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "error": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "lighthouse": {
      "type": "object",
      "properties": {
        "address": {
          "description": "MAC Address",
          "type": "string"
        },
        "name": {
          "description": "Human readable name",
          "type": "string"
        },
        "state": {
          "description": "What state the lighthouse is currently in",
          "type": "string",
          "enum": [
            "on",
            "off",
            "booting",
            "unknown"
          ]
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Lighthouse API",
    "version": "1.0"
  },
  "host": "localhost",
  "basePath": "/",
  "paths": {
    "/lighthouse": {
      "get": {
        "responses": {
          "200": {
            "description": "All known lighthouses",
            "schema": {
              "type": "object",
              "properties": {
                "address": {
                  "description": "MAC Address",
                  "type": "string"
                },
                "name": {
                  "description": "Human readable name",
                  "type": "string"
                },
                "state": {
                  "description": "What state the lighthouse is currently in",
                  "type": "string",
                  "enum": [
                    "on",
                    "off",
                    "booting",
                    "unknown"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/lighthouse/state": {
      "post": {
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "address": {
                  "definitions": {
                    "error": {
                      "type": "object",
                      "properties": {
                        "message": {
                          "type": "string"
                        }
                      }
                    },
                    "lighthouse": {
                      "type": "object",
                      "properties": {
                        "address": {
                          "description": "MAC Address",
                          "type": "string"
                        },
                        "name": {
                          "description": "Human readable name",
                          "type": "string"
                        },
                        "state": {
                          "description": "What state the lighthouse is currently in",
                          "type": "string",
                          "enum": [
                            "on",
                            "off",
                            "booting",
                            "unknown"
                          ]
                        }
                      }
                    }
                  },
                  "basePath": "/",
                  "host": "localhost",
                  "info": {
                    "title": "Lighthouse API",
                    "version": "1.0"
                  },
                  "paths": {
                    "/lighthouse": {
                      "get": {
                        "responses": {
                          "200": {
                            "description": "All known lighthouses",
                            "schema": {
                              "$ref": "#/definitions/lighthouse"
                            }
                          }
                        }
                      }
                    },
                    "/lighthouse/state": {
                      "post": {
                        "parameters": [
                          {
                            "in": "body",
                            "name": "body",
                            "schema": {
                              "properties": {
                                "address": {
                                  "$ref": "#definitions/lighthouse/properties/address"
                                },
                                "state": {
                                  "$ref": "#definitions/lighthouse/properties/state"
                                }
                              },
                              "type": "object"
                            }
                          }
                        ],
                        "responses": {
                          "200": {
                            "description": "State changed successfully",
                            "schema": {
                              "$ref": "#/definitions/lighthouse"
                            }
                          },
                          "400": {
                            "description": "Malformed request",
                            "schema": {
                              "$ref": "#/definitions/error"
                            }
                          },
                          "429": {
                            "description": "Rate limited (can only change state so often)",
                            "schema": {
                              "$ref": "#/definitions/error"
                            }
                          }
                        }
                      }
                    },
                    "/scan": {
                      "post": {
                        "parameters": [
                          {
                            "in": "body",
                            "name": "body",
                            "schema": {
                              "properties": {
                                "timeout": {
                                  "default": 5,
                                  "description": "how long to scan for (in seconds)",
                                  "maximum": 10,
                                  "minimum": 1,
                                  "type": "integer"
                                }
                              },
                              "type": "object"
                            }
                          }
                        ],
                        "responses": {
                          "200": {
                            "description": "Rescan successfully completed",
                            "schema": {
                              "$ref": "#/definitions/lighthouse"
                            }
                          },
                          "400": {
                            "description": "Malformed request",
                            "schema": {
                              "$ref": "#/definitions/error"
                            }
                          },
                          "429": {
                            "description": "Rate limited (can only rescan so often)",
                            "schema": {
                              "$ref": "#/definitions/error"
                            }
                          }
                        }
                      }
                    }
                  },
                  "schemes": [
                    "http"
                  ],
                  "swagger": "2.0"
                },
                "state": {
                  "definitions": {
                    "error": {
                      "type": "object",
                      "properties": {
                        "message": {
                          "type": "string"
                        }
                      }
                    },
                    "lighthouse": {
                      "type": "object",
                      "properties": {
                        "address": {
                          "description": "MAC Address",
                          "type": "string"
                        },
                        "name": {
                          "description": "Human readable name",
                          "type": "string"
                        },
                        "state": {
                          "description": "What state the lighthouse is currently in",
                          "type": "string",
                          "enum": [
                            "on",
                            "off",
                            "booting",
                            "unknown"
                          ]
                        }
                      }
                    }
                  },
                  "basePath": "/",
                  "host": "localhost",
                  "info": {
                    "title": "Lighthouse API",
                    "version": "1.0"
                  },
                  "paths": {
                    "/lighthouse": {
                      "get": {
                        "responses": {
                          "200": {
                            "description": "All known lighthouses",
                            "schema": {
                              "$ref": "#/definitions/lighthouse"
                            }
                          }
                        }
                      }
                    },
                    "/lighthouse/state": {
                      "post": {
                        "parameters": [
                          {
                            "in": "body",
                            "name": "body",
                            "schema": {
                              "properties": {
                                "address": {
                                  "basePath": "/",
                                  "definitions": {
                                    "error": {
                                      "properties": {
                                        "message": {
                                          "type": "string"
                                        }
                                      },
                                      "type": "object"
                                    },
                                    "lighthouse": {
                                      "properties": {
                                        "address": {
                                          "description": "MAC Address",
                                          "type": "string"
                                        },
                                        "name": {
                                          "description": "Human readable name",
                                          "type": "string"
                                        },
                                        "state": {
                                          "description": "What state the lighthouse is currently in",
                                          "enum": [
                                            "on",
                                            "off",
                                            "booting",
                                            "unknown"
                                          ],
                                          "type": "string"
                                        }
                                      },
                                      "type": "object"
                                    }
                                  },
                                  "host": "localhost",
                                  "info": {
                                    "title": "Lighthouse API",
                                    "version": "1.0"
                                  },
                                  "paths": {
                                    "/lighthouse": {
                                      "get": {
                                        "responses": {
                                          "200": {
                                            "description": "All known lighthouses",
                                            "schema": {
                                              "$ref": "#/definitions/lighthouse"
                                            }
                                          }
                                        }
                                      }
                                    },
                                    "/lighthouse/state": {
                                      "post": {
                                        "parameters": [
                                          {
                                            "in": "body",
                                            "name": "body",
                                            "schema": {
                                              "properties": {
                                                "address": {
                                                  "$ref": "#definitions/lighthouse/properties/address"
                                                },
                                                "state": {
                                                  "$ref": "#definitions/lighthouse/properties/state"
                                                }
                                              },
                                              "type": "object"
                                            }
                                          }
                                        ],
                                        "responses": {
                                          "200": {
                                            "description": "State changed successfully",
                                            "schema": {
                                              "$ref": "#/definitions/lighthouse"
                                            }
                                          },
                                          "400": {
                                            "description": "Malformed request",
                                            "schema": {
                                              "$ref": "#/definitions/error"
                                            }
                                          },
                                          "429": {
                                            "description": "Rate limited (can only change state so often)",
                                            "schema": {
                                              "$ref": "#/definitions/error"
                                            }
                                          }
                                        }
                                      }
                                    },
                                    "/scan": {
                                      "post": {
                                        "parameters": [
                                          {
                                            "in": "body",
                                            "name": "body",
                                            "schema": {
                                              "properties": {
                                                "timeout": {
                                                  "default": 5,
                                                  "description": "how long to scan for (in seconds)",
                                                  "maximum": 10,
                                                  "minimum": 1,
                                                  "type": "integer"
                                                }
                                              },
                                              "type": "object"
                                            }
                                          }
                                        ],
                                        "responses": {
                                          "200": {
                                            "description": "Rescan successfully completed",
                                            "schema": {
                                              "$ref": "#/definitions/lighthouse"
                                            }
                                          },
                                          "400": {
                                            "description": "Malformed request",
                                            "schema": {
                                              "$ref": "#/definitions/error"
                                            }
                                          },
                                          "429": {
                                            "description": "Rate limited (can only rescan so often)",
                                            "schema": {
                                              "$ref": "#/definitions/error"
                                            }
                                          }
                                        }
                                      }
                                    }
                                  },
                                  "schemes": [
                                    "http"
                                  ],
                                  "swagger": "2.0"
                                },
                                "state": {
                                  "$ref": "#definitions/lighthouse/properties/state"
                                }
                              },
                              "type": "object"
                            }
                          }
                        ],
                        "responses": {
                          "200": {
                            "description": "State changed successfully",
                            "schema": {
                              "$ref": "#/definitions/lighthouse"
                            }
                          },
                          "400": {
                            "description": "Malformed request",
                            "schema": {
                              "$ref": "#/definitions/error"
                            }
                          },
                          "429": {
                            "description": "Rate limited (can only change state so often)",
                            "schema": {
                              "$ref": "#/definitions/error"
                            }
                          }
                        }
                      }
                    },
                    "/scan": {
                      "post": {
                        "parameters": [
                          {
                            "in": "body",
                            "name": "body",
                            "schema": {
                              "properties": {
                                "timeout": {
                                  "default": 5,
                                  "description": "how long to scan for (in seconds)",
                                  "maximum": 10,
                                  "minimum": 1,
                                  "type": "integer"
                                }
                              },
                              "type": "object"
                            }
                          }
                        ],
                        "responses": {
                          "200": {
                            "description": "Rescan successfully completed",
                            "schema": {
                              "$ref": "#/definitions/lighthouse"
                            }
                          },
                          "400": {
                            "description": "Malformed request",
                            "schema": {
                              "$ref": "#/definitions/error"
                            }
                          },
                          "429": {
                            "description": "Rate limited (can only rescan so often)",
                            "schema": {
                              "$ref": "#/definitions/error"
                            }
                          }
                        }
                      }
                    }
                  },
                  "schemes": [
                    "http"
                  ],
                  "swagger": "2.0"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "State changed successfully",
            "schema": {
              "type": "object",
              "properties": {
                "address": {
                  "description": "MAC Address",
                  "type": "string"
                },
                "name": {
                  "description": "Human readable name",
                  "type": "string"
                },
                "state": {
                  "description": "What state the lighthouse is currently in",
                  "type": "string",
                  "enum": [
                    "on",
                    "off",
                    "booting",
                    "unknown"
                  ]
                }
              }
            }
          },
          "400": {
            "description": "Malformed request",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          },
          "429": {
            "description": "Rate limited (can only change state so often)",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/scan": {
      "post": {
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "timeout": {
                  "description": "how long to scan for (in seconds)",
                  "type": "integer",
                  "default": 5,
                  "maximum": 10,
                  "minimum": 1
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Rescan successfully completed",
            "schema": {
              "type": "object",
              "properties": {
                "address": {
                  "description": "MAC Address",
                  "type": "string"
                },
                "name": {
                  "description": "Human readable name",
                  "type": "string"
                },
                "state": {
                  "description": "What state the lighthouse is currently in",
                  "type": "string",
                  "enum": [
                    "on",
                    "off",
                    "booting",
                    "unknown"
                  ]
                }
              }
            }
          },
          "400": {
            "description": "Malformed request",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          },
          "429": {
            "description": "Rate limited (can only rescan so often)",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "error": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "lighthouse": {
      "type": "object",
      "properties": {
        "address": {
          "description": "MAC Address",
          "type": "string"
        },
        "name": {
          "description": "Human readable name",
          "type": "string"
        },
        "state": {
          "description": "What state the lighthouse is currently in",
          "type": "string",
          "enum": [
            "on",
            "off",
            "booting",
            "unknown"
          ]
        }
      }
    }
  }
}`))
}
